version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
        - image: circleci/python:3.6   # primary container for the build job
        steps:
        - checkout
        - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
        - run:
                command: |
                        python3 -m venv virt
                        . virt/bin/activate
                        pip install -r requirements.txt
        - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                        - "venv"
        - run:
                name: Running tests
                command: |
                        . virt/bin/activate
                        python3 test_one.py
        - store_artifacts:
                path: test-reports/
                destination: pydoge_tsip

              
